# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: AWS ElasticBeanstalk Deployment

env:
  APP_NAME: portafolio
  ENV_NAME: Portafolio-env
  AWS_REGION: us-east-2
  AWS_PLATFORM: node.js
  PIPELINE_ID: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}

on:
  push:
    paths:
      - 'backend/**'
      - '!backend/nest-cli.json'
      - '!backend/README.md'
      - '.github/workflows/awsBackend.yml'
defaults:
  run:
    working-directory: ./backend
jobs:
  build:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
    # Acá se baja el repo en la rama que se pushó
    - uses: actions/checkout@v4
    # Se cachea el node modules
    - name: Cache node modules
      uses: actions/cache@v4
      env:
        cache-name: node-modules
      with:
        path: backend/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - run: yarn
    - run: yarn build
    - run: ls -l
    - name: Create Backend Bundle
      run: |
        zip -r ${{env.APP_NAME}}.zip ./node_modules ./dist package.json .ebextensions .platform
    - name: Upload build-bundle
      uses: actions/upload-artifact@v4
      with:
        name: build-bundle
        path: |
          backend/${{env.APP_NAME}}.zip
  deploy_aws:
    needs: [build]
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Download backend bundle
        uses: actions/download-artifact@v4
        with:
          name: build-bundle
          path: backend/
      - name: Unzip bundle
        run: unzip ${{env.APP_NAME}}.zip
      - name: Remove zip artifact
        run: rm -f ${{env.APP_NAME}}.zip
      - name: Check up on files
        run: ls -l
      - name: Set up Python 3.6 (needed for eb cli)
        uses: actions/setup-python@v5
        with:
          python-version: "3.6"
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Install AWS EB CLI
        run: |
          echo "Installing Elastic Beanstalk Cli"
          python -m pip install --upgrade pip
          pip install awsebcli --upgrade
          eb --version
      - name: EB CLI init
        run: |
          eb init "${{env.APP_NAME}}" -p "${{env.AWS_PLATFORM}}" --region ${{env.AWS_REGION}}
          eb use "${{env.ENV_NAME}}"
      - name: EB CLI deploy
        run: eb deploy -v --region ${{ env.AWS_REGION }}
