# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Github Pages Deployment

on: [push, pull_request]
defaults:
  run:
    working-directory: ./front
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ./node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-v2-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - run: yarn
    - run: yarn build
    - name: Cache build
      uses: actions/cache@v2
      env:
        cache-name: cache-build
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ./public
        key: ${{ env.cache-name }}-${{ github.sha }}
  deploy:
    needs: build
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache build
        uses: actions/cache@v2
        env:
          cache-name: cache-build
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ./public
          key: ${{ env.cache-name }}-${{ github.sha }}
      - name: See folder files
        run: ls
      - name: Deploy to Github Pages
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './public'
          destination-github-username: 'Japsz'
          destination-repository-name: 'japsz.github.io'
          user-email: benjamin.meneses.14@sansano.usm.cl
          target-branch: main
