# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Github Pages Deployment

on:
  push:
    paths:
      - 'front/**'
      - '!front/README.md'
defaults:
  run:
    working-directory: ./front
jobs:
  build:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
    # Acá se baja el repo en la rama que se pushó
    - uses: actions/checkout@v4
    # Se cachea el node modules
    - name: Cache node modules
      uses: actions/cache@v4
      env:
        cache-name: node-modules
      with:
        path: front/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - run: yarn
    - run: yarn build
    - run: ls -l
    - name: Deploy to Github Pages
      uses: datacake/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: front/public/.
        destination_repo: 'japsz/japsz.github.io'
        user_email: benjamin.meneses.14@sansano.usm.cl
        user_name: 'japsz'
