# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Github Pages Deployment

on: [push, pull_request]
defaults:
  run:
    working-directory: ./front
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.yarn
        key: ${{ runner.os }}-build-${{ env.cache-name }}-v10-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - run: yarn
    - run: yarn build
    - run: ls -l
    - name: Deploy to Github Pages
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      with:
        source-file: 'public'
        destination_repo: 'Japsz/japsz.github.io'
        user_email: benjamin.meneses.14@sansano.usm.cl
        user_name: 'Japsz'